print(true && true)
print(true && false)
print(false && true)
print(false && false)
print(true || true)
print(true || false)
print(false || true)
print(false || false)
print(~ false)
print(~ true)
print(~ (3<2 && 2<3) || 3-1=3)
